### ISSUE TITLE
Unable to find pandoc executable when using on Mac OS (brew)

### ISSUE THREAD

**Issue by EyMaddis** [larlequin/PandocAcademic#26]
Hi,
I have pandoc installed via `brew install pandoc` on MacOS Sierra.
When I try to execute the PDF conversion, I will get this error:
![image](https://cloud.githubusercontent.com/assets/1409100/21766303/db271c14-d66d-11e6-9f94-b43efafa5a41.png)

It seems that it cannot find the `pandoc` and `xdg-open` executable, here is the stacktrace from the Sublime 

```
error: Unable to execute Pandoc.                                    

Details: [Errno 2] No such file or directory: 'pandoc'
Unable to convert the file! Please check your options
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "PandocConvertor in /Users/maddis/Library/Application Support/Sublime Text 3/Installed Packages/Pandoc Academic.sublime-package", line 217, in run
  File "./python3.3/subprocess.py", line 523, in call
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open'
```

`pandoc` is available in the PATH when using the terminal. Also the equivalent to using `xdg-open` on MacOS is the `open` command, maybe there could be a switch statement based on the OS.

**Comment by larlequin** [comment]
Hi,

Not sure about this problem since I don’t have access to a Mac at this time. The fact that you used Brew to install Pandoc may explain why SublimeText could not find Pandoc. As for the xdg-open issue, you could try to comment the lines 216-217 of the "PandocConvertor.py".

Yet, I would recommend to install Pandoc using the  pkg installer for MacOs (see http://pandoc.org/installing.html) and see if that resolve the problems.

Best,

Guillaume
